# Generated by Django 4.1.2 on 2022-10-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONSTROL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
                ('NAME', models.CharField(max_length=255)),
            ],
        ),
    ]
