# Generated by Django 4.1.2 on 2022-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constrol',
            name='TYPE',
            field=models.CharField(choices=[('Quạt', 'Quạt'), ('Quạt trần', 'Quạt trần'), ('Điều hòa', 'Điều hòa'), ('Máy bơn nước', 'Máy bơn nước'), ('Bóng đèn', 'Bóng đèn')], max_length=50, null=True),
        ),
    ]
