# Generated by Django 4.1.7 on 2023-03-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0002_constrol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constrol',
            name='id_NAME',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constrol',
            name='TYPE',
            field=models.CharField(choices=[('Quạt', 'Quạt'), ('Quạt trần', 'Quạt trần'), ('Điều hòa', 'Điều hòa'), ('Máy bơn nước', 'Máy bơn nước'), ('Bóng đèn', 'Bóng đèn')], max_length=50),
        ),
    ]
