# Generated by Django 4.1.7 on 2023-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0003_constrol_id_name_alter_constrol_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BongDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DieuHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MayChieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quat_Tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.IntegerField(default=0)),
            ],
        ),
    ]
