# Generated by Django 4.1.7 on 2023-03-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0004_bongden_dieuhoa_maychieu_quat_quat_tran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constrol',
            name='id_NAME',
        ),
    ]
