# Generated by Django 4.1.7 on 2023-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0005_remove_constrol_id_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constrol',
            old_name='STATUS',
            new_name='STATUS_BongDen',
        ),
        migrations.AddField(
            model_name='constrol',
            name='STATUS_DieuHoa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constrol',
            name='STATUS_Quat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constrol',
            name='STATUS_QuatTran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constrol',
            name='TYPE',
            field=models.CharField(choices=[('Quạt', 'Quạt'), ('Quạt trần', 'Quạt trần'), ('Điều hòa', 'Điều hòa'), ('Bóng đèn', 'Bóng đèn')], max_length=50),
        ),
    ]
